/**
 * try{
 * 
 * 
 * }catch(error){
 *  console.log(worn);
 * }
 */

try{
    throw "the error"
}catch(error){
    console.log("error is: ",error)
}